const transactionData = [
    {
        "message": "Success",
        "transactionId": "TXN000001",
        "transaction": {
            "id": 1,
            "transactionReference": "TXN000001",
            "status": "BLOCKED",
            "paymentType": "WALLET",
            "amount": 236.0,
            "issueDate": "2024-01-06T20:00:28.000+00:00",
            "expiryDate": "2024-01-06T20:00:28.000+00:00",
            "donorId": 1,
            "beneficiaryId": 1,
            "agentId": 1,
            "fraisTransfert": 6.686953161783536,
            "whoPayFees": "Donor",
            "clientResponse": {
                "id": 1,
                "title": "ELGARAI",
                "prenom": "Hamza",
                "typePieceIdentite": "CIN",
                "paysEmissionPieceIdentite": "Maroc",
                "numeroPieceIdentite": "EE930320",
                "expirationPieceIdentite": "2025-12-31T23:00:00.000+00:00",
                "dateNaissance": "2001-10-24T00:00:00.000+00:00",
                "profession": "Etudiant",
                "paysNationalite": "Marocain",
                "paysAdresse": "Marrakech, Maroc",
                "adresseLegale": "ADRAR 2 MHAMID MARRAKECH",
                "ville": "Marrakech",
                "gsm": "0634348550",
                "email": "hamzaelgarai10@gmail.com",
                "agentResponse": {
                    "id": 1,
                    "nom": "Atlas",
                    "prenom": "Abdelghafour",
                    "email": "atlas@gmail.com",
                    "phone": "0600225588",
                    "solde": 5000.0
                },
                "solde": null,
                "beneficiaires": null
            },
            "beneficiaryResponse": {
                "id": 1,
                "nom": "ELGARAI",
                "prenom": "Karim",
                "email": "karimeg@yahoo.fr",
                "phone": "0632579630",
                "isBlockListed": false,
                "walletCode": "hxxx23",
                "walletClient": null
            },
            "notificationFees": false,
            "refundReason": null
        },
        "generatedOTP": null
    },
    {
        "message": "Success",
        "transactionId": "TXN000001",
        "transaction": {
            "id": 1,
            "transactionReference": "TXN000001",
            "status": "BLOCKED",
            "paymentType": "WALLET",
            "amount": 236.0,
            "issueDate": "2024-01-06T20:00:28.000+00:00",
            "expiryDate": "2024-01-06T20:00:28.000+00:00",
            "donorId": 1,
            "beneficiaryId": 1,
            "agentId": 1,
            "fraisTransfert": 6.686953161783536,
            "whoPayFees": "Donor",
            "clientResponse": {
                "id": 1,
                "title": "ELGARAI",
                "prenom": "Hamza",
                "typePieceIdentite": "CIN",
                "paysEmissionPieceIdentite": "Maroc",
                "numeroPieceIdentite": "EE930320",
                "expirationPieceIdentite": "2025-12-31T23:00:00.000+00:00",
                "dateNaissance": "2001-10-24T00:00:00.000+00:00",
                "profession": "Etudiant",
                "paysNationalite": "Marocain",
                "paysAdresse": "Marrakech, Maroc",
                "adresseLegale": "ADRAR 2 MHAMID MARRAKECH",
                "ville": "Marrakech",
                "gsm": "0634348550",
                "email": "hamzaelgarai10@gmail.com",
                "agentResponse": {
                    "id": 1,
                    "nom": "Atlas",
                    "prenom": "Abdelghafour",
                    "email": "atlas@gmail.com",
                    "phone": "0600225588",
                    "solde": 5000.0
                },
                "solde": null,
                "beneficiaires": null
            },
            "beneficiaryResponse": {
                "id": 1,
                "nom": "ELGARAI",
                "prenom": "Karim",
                "email": "karimeg@yahoo.fr",
                "phone": "0632579630",
                "isBlockListed": false,
                "walletCode": "hxxx23",
                "walletClient": null
            },
            "notificationFees": false,
            "refundReason": null
        },
        "generatedOTP": null
    },
    {
        "message": "Success",
        "transactionId": "TXN000001",
        "transaction": {
            "id": 1,
            "transactionReference": "TXN000001",
            "status": "BLOCKED",
            "paymentType": "WALLET",
            "amount": 236.0,
            "issueDate": "2024-01-06T20:00:28.000+00:00",
            "expiryDate": "2024-01-06T20:00:28.000+00:00",
            "donorId": 1,
            "beneficiaryId": 1,
            "agentId": 1,
            "fraisTransfert": 6.686953161783536,
            "whoPayFees": "Donor",
            "clientResponse": {
                "id": 1,
                "title": "ELGARAI",
                "prenom": "Hamza",
                "typePieceIdentite": "CIN",
                "paysEmissionPieceIdentite": "Maroc",
                "numeroPieceIdentite": "EE930320",
                "expirationPieceIdentite": "2025-12-31T23:00:00.000+00:00",
                "dateNaissance": "2001-10-24T00:00:00.000+00:00",
                "profession": "Etudiant",
                "paysNationalite": "Marocain",
                "paysAdresse": "Marrakech, Maroc",
                "adresseLegale": "ADRAR 2 MHAMID MARRAKECH",
                "ville": "Marrakech",
                "gsm": "0634348550",
                "email": "hamzaelgarai10@gmail.com",
                "agentResponse": {
                    "id": 1,
                    "nom": "Atlas",
                    "prenom": "Abdelghafour",
                    "email": "atlas@gmail.com",
                    "phone": "0600225588",
                    "solde": 5000.0
                },
                "solde": null,
                "beneficiaires": null
            },
            "beneficiaryResponse": {
                "id": 1,
                "nom": "ELGARAI",
                "prenom": "Karim",
                "email": "karimeg@yahoo.fr",
                "phone": "0632579630",
                "isBlockListed": false,
                "walletCode": "hxxx23",
                "walletClient": null
            },
            "notificationFees": false,
            "refundReason": null
        },
        "generatedOTP": null
    },
    {
        "message": "Success",
        "transactionId": "TXN000001",
        "transaction": {
            "id": 1,
            "transactionReference": "TXN000001",
            "status": "BLOCKED",
            "paymentType": "WALLET",
            "amount": 236.0,
            "issueDate": "2024-01-06T20:00:28.000+00:00",
            "expiryDate": "2024-01-06T20:00:28.000+00:00",
            "donorId": 1,
            "beneficiaryId": 1,
            "agentId": 1,
            "fraisTransfert": 6.686953161783536,
            "whoPayFees": "Donor",
            "clientResponse": {
                "id": 1,
                "title": "ELGARAI",
                "prenom": "Hamza",
                "typePieceIdentite": "CIN",
                "paysEmissionPieceIdentite": "Maroc",
                "numeroPieceIdentite": "EE930320",
                "expirationPieceIdentite": "2025-12-31T23:00:00.000+00:00",
                "dateNaissance": "2001-10-24T00:00:00.000+00:00",
                "profession": "Etudiant",
                "paysNationalite": "Marocain",
                "paysAdresse": "Marrakech, Maroc",
                "adresseLegale": "ADRAR 2 MHAMID MARRAKECH",
                "ville": "Marrakech",
                "gsm": "0634348550",
                "email": "hamzaelgarai10@gmail.com",
                "agentResponse": {
                    "id": 1,
                    "nom": "Atlas",
                    "prenom": "Abdelghafour",
                    "email": "atlas@gmail.com",
                    "phone": "0600225588",
                    "solde": 5000.0
                },
                "solde": null,
                "beneficiaires": null
            },
            "beneficiaryResponse": {
                "id": 1,
                "nom": "ELGARAI",
                "prenom": "Karim",
                "email": "karimeg@yahoo.fr",
                "phone": "0632579630",
                "isBlockListed": false,
                "walletCode": "hxxx23",
                "walletClient": null
            },
            "notificationFees": false,
            "refundReason": null
        },
        "generatedOTP": null
    }
]

export default transactionData